export const EN = {
	VWAP: 'VWAP',
	PREV_CLOSE: 'Prev. Close',
	OPEN: 'Open',
	CLOSE: 'Close',
	HIGH: 'High',
	LOW: 'Low',
	VOLUME: 'Volume',
	TURNOVER: 'Turnover',
	MAX: 'Max',
	MIN: 'Min',
	BID_OFFER: 'Bid/Offer',
	TRADES: 'Trades',
	BEST_BID: 'Best Bid',
	BEST_OFFER: 'Best Offer',
	BID_QTY: 'Bid Qty',
	OFFER_QTY: 'Offer Qty',
	TOTAL_BID_QTY: 'Total Bid Qty',
	TOTAL_OFFER_QTY: 'Total Offer Qty.',
	FIFTY_TWO_WK_LOW: '52 Wk. Low',
	FIFTY_TWO_WK_HIGH: '52 Wk. High',
	TIME: 'Time',
	PRICE: 'Price',
	QTY: 'Quantity',
	CHANGE: 'Change',
	PER_CHANGE: '% Change',
	SPLITS: 'Splits',
	TICK: 'Tick',
	SIDE: 'Side',
	BUY: 'Buy',
	SELL: 'Sell',
};
