export const priceResponseTypes = {
	string: 1,
	number: 2,
	boolean: 3,
};

export const priceResponseTags = {
	3: { tag: 'symbolCode', type: priceResponseTypes.string },
	4: { tag: 'exchangeCode', type: priceResponseTypes.string },
	10: { tag: 'bestAskPrice', type: priceResponseTypes.number },
	11: { tag: 'bestAskQty', type: priceResponseTypes.number },
	12: { tag: 'bestBidPrice', type: priceResponseTypes.number },
	13: { tag: 'bestBidQty', type: priceResponseTypes.number },
	16: { tag: 'totalBidQty', type: priceResponseTypes.number },
	17: { tag: 'totalAskQty', type: priceResponseTypes.number },
	30: { tag: 'highPrice', type: priceResponseTypes.number },
	31: { tag: 'lowPrice', type: priceResponseTypes.number },
	32: { tag: 'closePrice', type: priceResponseTypes.number },
	33: { tag: 'openPrice', type: priceResponseTypes.number },
	34: { tag: 'change', type: priceResponseTypes.number },
	35: { tag: 'perChange', type: priceResponseTypes.number },
	36: { tag: 'previousClosePrice', type: priceResponseTypes.number },
	37: { tag: 'turnover', type: priceResponseTypes.number },
	38: { tag: 'volume', type: priceResponseTypes.number },
	43: { tag: 'marketDate', type: priceResponseTypes.string },
	52: { tag: 'splits', type: priceResponseTypes.string },
	53: { tag: 'time', type: priceResponseTypes.string },
	54: { tag: 'sequence', type: priceResponseTypes.number },
	55: { tag: 'lastTradePrice', type: priceResponseTypes.number },
	56: { tag: 'totalQty', type: priceResponseTypes.number },
	62: { tag: 'vwap', type: priceResponseTypes.string },
	67: { tag: 'type', type: priceResponseTypes.string },
	75: { tag: 'trades', type: priceResponseTypes.number },
	77: { tag: 'lastTradedPrice', type: priceResponseTypes.number },
	80: { tag: 'max', type: priceResponseTypes.number },
	81: { tag: 'min', type: priceResponseTypes.number },
	82: { tag: 'high52', type: priceResponseTypes.number },
	84: { tag: 'low52', type: priceResponseTypes.number },
	221: { tag: 'depthType', type: priceResponseTypes.string },
	222: { tag: 'depthID', type: priceResponseTypes.string },
	227: { tag: 'depthType', type: priceResponseTypes.string },
	228: { tag: 'depthID', type: priceResponseTypes.string },
	226: { tag: 'depthSplit', type: priceResponseTypes.string },
	225: { tag: 'depthQty', type: priceResponseTypes.number },
	224: { tag: 'depthValue', type: priceResponseTypes.number },
	220: { tag: 'depthQty', type: priceResponseTypes.number },
	219: { tag: 'depthValue', type: priceResponseTypes.number },
	403: { tag: 'date', type: priceResponseTypes.number },
	635: { tag: 'lastTradeDate', type: priceResponseTypes.string },
	640: { tag: 'date', type: priceResponseTypes.string },
	800: { tag: 'date', type: priceResponseTypes.string },
	801: { tag: 'unrealizedReturn', type: priceResponseTypes.number },
	802: { tag: 'remainingPotential', type: priceResponseTypes.number },
	803: { tag: 'report', type: priceResponseTypes.string },
	804: { tag: 'title', type: priceResponseTypes.string },
	805: { tag: 'takeProfit', type: priceResponseTypes.string },
	806: { tag: 'stopLoss', type: priceResponseTypes.number },
	807: { tag: 'entryPrice', type: priceResponseTypes.number },
	809: { tag: 'action', type: priceResponseTypes.string },
	811: { tag: 'gicsL4', type: priceResponseTypes.number },
	813: { tag: 'exitPrice', type: priceResponseTypes.number },

	EXCHANGE: { tag: 'exchangeCode', type: priceResponseTypes.string },
	SYMBOL: { tag: 'symbolCode', type: priceResponseTypes.string },
	INSTRUMENT_TYPE: { tag: 'instrumentType', type: priceResponseTypes.string },
	SYMBOL_DESCRIPTION: { tag: 'longDesc', type: priceResponseTypes.string },
	CURRENCY: { tag: 'currency', type: priceResponseTypes.string },
	SHRT_DSC: { tag: 'shortDesc', type: priceResponseTypes.string },
	DECIMAL_PLACES: { tag: 'decimalPlaces', type: priceResponseTypes.number },
	CORRECTION_FACTOR: { tag: 'decimalCorrectionFactor', type: priceResponseTypes.number },
	DS: { tag: 'dispCode', type: priceResponseTypes.string },
	DES: { tag: 'des', type: priceResponseTypes.string },
	SDES: { tag: 'sDes', type: priceResponseTypes.string },
	CON: { tag: 'contry', type: priceResponseTypes.string },
	CAT: { tag: 'cat', type: priceResponseTypes.string },
	SECTOR: { tag: 'sectorCode', type: priceResponseTypes.string },
	S: { tag: 'indexSymbolCode', type: priceResponseTypes.string },
	L: { tag: 'language', type: priceResponseTypes.string },
	SEC: { tag: 'section', type: priceResponseTypes.string },
	SYMT: { tag: 'symt', type: priceResponseTypes.string },
	SD: { tag: 'startDate', type: priceResponseTypes.string },
	ED: { tag: 'endDate', type: priceResponseTypes.string },
	IPC: { tag: 'indexPercentageChange', type: priceResponseTypes.number },
	PL: { tag: 'realizedProfit', type: priceResponseTypes.number },
	CID: { tag: 'companyId', type: priceResponseTypes.string },
	E: { tag: 'exchangeCode', type: priceResponseTypes.string },
	BS: { tag: 'symbolCode', type: priceResponseTypes.string },
	BRATE: { tag: 'bestSymbolRate', type: priceResponseTypes.number },
	SRATE: { tag: 'successRate', type: priceResponseTypes.number },
	ARTN: { tag: 'averageReturn', type: priceResponseTypes.number },
	MIP: { tag: 'marketIndex', type: priceResponseTypes.string },
	EXG: { tag: 'exchangeCode', type: priceResponseTypes.string },
	SYM: { tag: 'symbolCode', type: priceResponseTypes.string },
	DUR: { tag: 'duration', type: priceResponseTypes.string },
	VALUE: { tag: 'value', type: priceResponseTypes.string  },
	GEO: { tag: 'region', type: priceResponseTypes.string },
	CLASS : { tag: 'riskType', type: priceResponseTypes.string },
	DESCR: { tag: 'description', type: priceResponseTypes.string },
	DESC: { tag: 'description', type: priceResponseTypes.string },
	FULL: { tag: 'fullDescription', type: priceResponseTypes.string },
	SHORT: { tag: 'shortDescription', type: priceResponseTypes.string },
	CUR: { tag: 'currency', type: priceResponseTypes.string },
	BENM: { tag: 'benchMark', type: priceResponseTypes.string },
	PCT1M: { tag: 'percentageOneMonth', type: priceResponseTypes.number },
	PCT3M: { tag: 'percentageThreeMonth', type: priceResponseTypes.number },
	DATE: { tag: 'date', type: priceResponseTypes.string },
	EXPR: { tag: 'expenseRatio', type: priceResponseTypes.number },
	HOLD: { tag: 'holdings', type: priceResponseTypes.number },
	MCAP: { tag: 'averageMarketCap', type: priceResponseTypes.number },
	PE: { tag: 'profitEarnings', type: priceResponseTypes.number },
	RET: { tag: 'return', type: priceResponseTypes.number },
	IR: { tag: 'informationRatio', type: priceResponseTypes.number },
	R2: { tag: 'R2', type: priceResponseTypes.string },
	TE: { tag: 'trackingError', type: priceResponseTypes.string },
	SHP: { tag: 'sharpeRatio', type: priceResponseTypes.number },
	STOK: { tag: 'stock', type: priceResponseTypes.number },
	BOND: { tag: 'bond', type: priceResponseTypes.number },
	CASH: { tag: 'cash', type: priceResponseTypes.number },
	OTHR: { tag: 'other', type: priceResponseTypes.string },
	ID: { tag: 'id', type: priceResponseTypes.string },
	M6: { tag: 'M6', type: priceResponseTypes.number },
	Y1: { tag: 'Y1', type: priceResponseTypes.number },
	Y3: { tag: 'Y3', type: priceResponseTypes.number },
	Y5: { tag: 'Y5', type: priceResponseTypes.number },
	YEAR: { tag: 'year', type: priceResponseTypes.number },
	MONTH: { tag: 'month', type: priceResponseTypes.number },
	FILE: { tag: 'file', type: priceResponseTypes.string },
	STDEV: { tag: 'stdDeviation', type: priceResponseTypes.string },
	EXRAT: { tag: 'excessReturn', type: priceResponseTypes.number },

	// refatcor below
	/*0: 'NODATA',
	5: 'EXC',
	6: 'INS',
	39: 'UP',
	40: 'DOWN',
	41: 'NOCHG',
	42: 'MSTAT',
	44: 'MTIM',
	45: 'CUR',
	75: 'NOT',
	50: 'SYMTRD',
    57: 'OL',
	65: 'ALT_TYP',
	66: 'ALT_ID',
	68: 'MSG_TYP',
	72: 'NWS_CAT',
	73: 'LTQ',
	74: 'TRT',
	78: 'STS',
	79: 'OPERATOR',
	85: 'SYMBOL',
	86: 'FREQ',
	100: 'SIGNAL_TYPE',
	110: 'SIGNAL_SUB_TYPE',
	111: 'SIGNAL_STRTGY',
	101: 'SIGNAL_ID',
	102: 'SIGNAL_TI',
	103: 'SIGNAL_SIDE',
	104: 'SIGNAL_TIME',
	105: 'SIGNAL_PRICE',
	106: 'SIGNAL_MSG_STATUS',
	107: 'SIGNAL_LAST_PRI',
	112: 'YTD_PCHG',
	113: 'SIGNAL_INTERVAL',
	123: 'TDES',
	125: 'DEP',
	130: 'ISIN',
	131: 'OPEN_INTEREST',
	135: 'MARKET_CODE',
	138: 'STRTGY',
	145: 'PER',
	146: 'MARKETCAP',
	155: 'EPS',
	157: 'REFP',
	346: 'NWPRV',
	348: 'NWID',
	349: 'NWD',
	350: 'LN',
	351: 'NWHD',
	354: 'NWSRC',
	361: 'NWSHOT',
	371: 'NWCT',
	372: 'ANTIM',
	373: 'ANID',
	374: 'ANHED',
	375: 'ANBOD',
	383: 'ANSYM',
	398: 'TTYP',
	463: 'CIT',
	466: 'COT',
	473: 'LUD',
	635: 'DATE',
	808: 'ALERT_ID',
	810: 'BASE_SYMBOL',
	812: 'ADVICE_STATUS',
	830: 'MSG_STATUS',
	831: 'RESEARCH_ID',
	832: 'REPORT_TYPE',
	833: 'PUBLISH_DATE',
	834: 'COUNTRY_CODES',
	835: 'GICS_CODES',
	836: 'AGENT_CODE',
	837: 'RESEARCH_TITLE',
	838: 'DESCRIPTION',
	839: 'HTML_URL',
	840: 'PDF_URL',
	841: 'WEB_URL',
	842: 'RESEARCH_IMAGE_URL',
	843: 'RESEARCH_SYMBOL_LIST',
	844: 'RESEARCH_TIME',
	850: 'NOTIFICATION_ID',
	2015: 'CID',
	11006: 'DE',
	11023: 'SDES',
	11039: 'DES',
	11044: 'DS',
	12370: 'TYPE',
	12590: 'TITLE',
	12240: 'SYMSTS',
	12402 : 'CA_ID',
	12743: 'YTD_CHG',
	17380: 'AV5D',
	23815: 'STATUS',
	24037: 'YEARLY_PCT_CHANGE',
	25828: 'ANN_INDICATOR',
	25827: 'NWS_INDICATOR',
	26328: 'WEEKLY_PCT_CHANGE',
	25127: 'NWS_EDITORIAL_ID',*/
};
