
export const EN = {
	VWAP: 'VWAP',
	PREV_CLOSE: 'Prev. Close',
	OPEN: 'Open',
	CLOSE: 'Close',
	HIGH: 'High',
	LOW: 'Low',
	VOLUME: 'Volume',
	TURNOVER: 'Turnover',
	MAX: 'Max',
	MIN: 'Min',
	BID_OFFER: 'Bid/Offer',
	TRADES: 'Trades',
	BEST_BID: 'Best Bid',
	BEST_OFFER: 'Best Offer',
	BID_QTY: 'Bid Qty',
	OFFER_QTY: 'Offer Qty',
	TOTAL_BID_QTY: 'Total Bid Qty',
	TOTAL_OFFER_QTY: 'Total Offer Qty.',
	FIFTY_TWO_WK_LOW: '52 Wk. Low',
	FIFTY_TWO_WK_HIGH: '52 Wk. High',
	TIME: 'Time',
	PRICE: 'Price',
	QTY: 'Quantity',
	CHANGE: 'Change',
	PER_CHANGE: '% Change',
	SPLITS: 'Splits',
	TICK: 'Tick',
	SIDE: 'Side',
	BUY: 'Buy',
	SELL: 'Sell',
	DAY_RANGE: 'Day Range',
	FIFTY_TWO_WK_RANGE: '52 Wk. Range',
	USERNAME: 'Username',
	PASSWORD: 'Password',
	REMEMBER_ME: 'Remember me',
	FORGOT_PASSWORD: 'Forgot Password?',
	LOGIN: 'Login',
	SPREAD_PER: 'Spread(%)',
	SPREAD: 'Spread',
	RANGE_PER: 'Range(%)',
	RANGE: 'Range',
	OFFER: 'Offer',
	BID: 'Bid',
	SEQ: 'Seq.',
	BY_ORDER: 'By Order',
	BY_PRICE: 'By Price',
	JAN: 'Jan',
	FEB: 'Feb',
	MAR: 'Mar',
	APR: 'Apr',
	MAY: 'May',
	JUN: 'Jun',
	JUL: 'Jul',
	AUG: 'Aug',
	SEP: 'Sep',
	OCT: 'Oct',
	NOV: 'Nov',
	DEC: 'Dec',
	MF_STRATEGY_1: 'Growth Strategy',
	MF_STRATEGY_2: 'Balanced Strategy',
	MF_STRATEGY_3: 'Pruedent  Strategy',
	MF_REGION_TITLE_1: 'Mubasher Regional Strategies',
	MF_REGION_TITLE_2: 'Mubasher Global Strategies',
	MF_REGION_TITLE_3: 'Mubasher Sharia Compliant Strategies',
	MF_STRT_PERFOM: 'Strategies Performance',
	ANNUALIZED_PCNT: 'Annualized %',
	MF_CHART_FOOTER_DES: '* Performance is annualized. Past performance is not guarantee for future performance',
	YEAR_5: '5Y',
	YEAR_3: '3Y',
	YEAR_1: '1Y',
	MONTHS_6: '6M',
	STRATEGY: 'Strategy',
	LAST_MONTH_PCNT : 'Last Month %',
	LAST_3MONTH_PCNT: 'Last 3M %',
	MORE: 'More',
};
